[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
cache_path  = 'cache_forge'
solc = '0.8.20'
optimizer = false
optimizer-runs = 999
fs_permissions = [{ access = "read-write", path = "./data" }]
gas_reports = ["Auctioneer", "AuctioneerHarness", "AuctioneerFarm"]